apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 167710399293.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 167710399293.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: 8d487d30
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
